POST http://localhost:8080/api/manager/
Content-Type: application/json
Accept: application/json

{
"name": {
"firstname": "Cemil",
"subname": "Halo",
"lastname": "Aslan"
},
"gender": "MALE",
"phonenumber": {
"countrycode": "43",
"areacode": "664",
"serialnumber": "1840791"
},
"title": {
"grade": "B",
"subjectgrade": "ARTS"
},
"address": {
"street": "Pernerstorfergasse 60/3/18",
"zipcode": "1100",
"place": "Vienna"
},
  "birthDate": "2002-03-20"

}
###

GET http://localhost:8080/api/manager/
Content-Type: application/json
Accept: application/json
###

GET http://localhost:8080/api/manager/1
Content-Type: application/json
Accept: application/json
###

PATCH http://localhost:8080/api/manager/1
Content-Type: application/json
Accept: application/json

{
  "gender": "FEMALE"

}
###
DELETE http://localhost:8080/api/manager/1
Content-Type: application/json
Accept: application/json

{
  "name": {
    "firstname": "Cemil",
    "subname": "Halo",
    "lastname": "Aslan"
  },
  "gender": "MALE",
  "phonenumber": {
    "countrycode": "43",
    "areacode": "664",
    "serialnumber": "1840791"
  },
  "title": {
    "grade": "B",
    "subjectgrade": "ARTS"
  },
  "address": {
    "street": "Pernerstorfergasse 60/3/18",
    "zipcode": "1100",
    "place": "Vienna"
  },
  "birthDate": "2002-03-20"

}
###