POST http://localhost:5000/api/secretary/
Content-Type: application/json
Accept: application/json

{
  "name" : {
    "firstname": "Sel",
    "subname": "Ilyas",
    "lastname": "Tan"
  },
  "gender": "MALE",
  "phonenumber": {
    "countrycode": "+43",
    "areacode": "660",
    "serialnumber": "3170155"
  },
  "title": {
    "grade": "M",
    "subjectGrade": "SCIENCE"
  },
  "address": {
    "street": "Zehdengasse 12",
    "zipcode": "1220",
    "place": "Wien"
  },
  "birthDate": "2004-04-09",

  "ordination": {
    "abbrevitation": "DE",
    "name": "Dermanzentrum",
    "address": {
      "street": "Zehdengasse 12",
      "zipcode": "1220",
      "place": "Wien"
    }
  }

  }
###

PUT http://localhost:5000/api/secretary/2
Content-Type: application/json
Accept: application/json

{
  "name" : {
    "firstname": "Markus",
    "subname": "Zirkus",
    "lastname": "Padurea"
  },
  "gender": "MALE",
  "phonenumber": {
    "countrycode": "+43",
    "areacode": "613",
    "serialnumber": "567911"
  },
  "title": {
    "grade": "M",
    "subjectGrade": "ENGINEERING"
  },
  "address": {
    "street": "Gumpendorferstrasse 14",
    "zipcode": "1200",
    "place": "Wien"
  },
  "birthDate": "2004-02-20"
}
###

POST http://localhost:5000/api/secretary/
Content-Type: application/json
Accept: application/json

{
  "name" : {
    "firstname": "Cemil",
    "subname": "Dumus",
    "lastname": "Aslan"
  },
  "gender": "MALE",
  "phonenumber": {
    "countrycode": "+43",
    "areacode": "678",
    "serialnumber": "4517991"
  },
  "title": {
    "grade": "DIPL",
    "subjectGrade": "PHIL"
  },
  "address": {
    "street": "Erlachplatz 24",
    "zipcode": "1100",
    "place": "Wien"
  },
  "birthDate": "2002-03-20"
}
###

PATCH http://localhost:5000/api/secretary/1
Content-Type: application/json
Accept: application/json

{
   "birthDate": "2002-03-20"
}
###



GET http://localhost:5000/api/secretary/
Content-Type: application/json
Accept: application/json
###

GET http://localhost:5000/api/secretary/2
Content-Type: application/json
Accept: application/json
###

DELETE http://localhost:5000/api/secretary/1
Content-Type: application/json
Accept: application/json
###

DELETE http://localhost:5000/api/secretary/
Content-Type: application/json
Accept: application/json

###